services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    environment:
      - PORT=8787
      - BIND_HOST=0.0.0.0
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8787/_api/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    ports:
      - "8787:8787"
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    depends_on:
      - api
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    ports:
      - "3000:80"
