version: '3.8'
services:
  api:
    build: ./api
    ports:
      - 127.0.0.1:8080:8080
    volumes:
      - ./data:/data
    environment:
      - FLASK_ENV=development
      - SECRET_TOKEN=changeme
    restart: unless-stopped
