name: CI Health Check

on:
  push:
    branches: [ci/docker-matrix-fix]

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Echo
        run: |
          echo "CI Health Check: runner available"
