name: CI (pnpm monorepo)

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
  push:
    # run on pushes to any branch (helps branch builds and CI feedback)
    branches: ['**']

jobs:
  monorepo-checks:
    name: Monorepo lint/typecheck/test/build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install pnpm
        run: npm install -g pnpm@9

      - name: Install dependencies (workspace)
        run: pnpm -w install --frozen-lockfile

      - name: Run lint across workspace (if present)
        run: pnpm -w -r lint --if-present

      - name: Run typecheck across workspace (if present)
        run: pnpm -w -r typecheck --if-present

      - name: Run tests across workspace (if present)
        run: pnpm -w -r test --if-present

      - name: Build packages (if present)
        run: pnpm -w -r build --if-present

      - name: Upload pnpm lockfile as artifact (for debugging CI failures)
        uses: actions/upload-artifact@v4
        with:
          name: pnpm-lock
          path: pnpm-lock.yaml

