name: CI
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  monorepo-checks:
    name: Monorepo lint/typecheck/test/build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

      - name: Load TRACK into environment
        if: always()
        run: |
          if [ -f TRACK ]; then
            echo "TRACK=$(cat TRACK)" >> $GITHUB_ENV
          fi

      - name: Setup Node.js
        uses: actions/setup-node@1e60f620b9540f58f3dc1cb8b01260c4d8c1d9da
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Enable corepack & prepare pnpm
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate

      - name: Install dependencies (workspace)
        run: pnpm -w install --frozen-lockfile

      - name: Run lint across workspace (if present)
        run: pnpm -w -r run lint --if-present

      - name: Run typecheck across workspace (if present)
        run: pnpm -w -r run typecheck --if-present

      - name: Run tests across workspace (if present)
        run: pnpm -w -r run test --if-present

      - name: Build packages (if present)
        run: pnpm -w -r run build --if-present
      - name: Upload pnpm lockfile
        uses: actions/upload-artifact@v4
        with:
          name: pnpm-lock
          path: pnpm-lock.yaml
