name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        workspace:
          - apps/api-cli
          - apps/admin-web
          - apps/web
          - packages/core
          - packages/admin-api
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Lint
        run: pnpm --filter ./${{ matrix.workspace }} lint || echo "No lint script"
      - name: Typecheck
        run: pnpm --filter ./${{ matrix.workspace }} typecheck || echo "No typecheck script"
      - name: Test
        run: pnpm --filter ./${{ matrix.workspace }} test --if-present || echo "No test script"
      - name: Build
        run: pnpm --filter ./${{ matrix.workspace }} build
