name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: [20, 22]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Enable corepack / pnpm
        run: |
          corepack enable
          corepack prepare pnpm@10.17.0 --activate
          pnpm -v

      - name: Cache pnpm store
        uses: actions/cache@v4
        with:
          path: ~/.local/share/pnpm/store
          key: pnpm-${{ runner.os }}-${{ matrix.node }}-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-${{ runner.os }}-${{ matrix.node }}-

      - name: Install
        run: pnpm install --frozen-lockfile

      - name: Lint (if present)
        run: |
          pnpm -r --silent run | grep -q '^lint$' && pnpm -r lint || echo "no lint scripts"

      - name: Typecheck (if present)
        run: |
          pnpm -r --silent run | grep -q '^typecheck$' && pnpm -r typecheck || echo "no typecheck scripts"

      - name: Test (if present)
        run: |
          pnpm -r --silent run | grep -q '^test$' && pnpm -r test || echo "no test scripts"

      - name: Build (if present)
        run: |
          pnpm -r --silent run | grep -q '^build$' && pnpm -r build || echo "no build scripts"

      - name: Build next-roadmap explicitly
        run: |
          pnpm --filter next-roadmap run build || echo "next-roadmap build failed" && exit 1

      - name: Upload next-roadmap .next
        uses: actions/upload-artifact@v4
        with:
          name: next-roadmap-build-${{ matrix.node }}
          path: apps/next-roadmap/.next
          if-no-files-found: ignore

      - name: Upload build artifacts (admin-web dist if exists)
        uses: actions/upload-artifact@v4
        with:
          name: admin-web-dist-${{ matrix.node }}
          path: apps/admin-web/dist
          if-no-files-found: ignore
