name: Ensure repo labels

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

permissions:
  issues: write

jobs:
  ensure-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Ensure labels exist
        uses: actions/github-script@v7
        with:
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const desired = [
              { name: 'needs-roadmap', color: 'd93f0b', description: 'PR needs a roadmap reference (added by PR assistant)' }
            ];

            const { data: existing } = await github.issues.listLabelsForRepo({ owner, repo });
            const existingNames = new Set(existing.map(l => l.name));

            for (const lbl of desired) {
              if (!existingNames.has(lbl.name)) {
                await github.issues.createLabel({ owner, repo, name: lbl.name, color: lbl.color, description: lbl.description });
                core.info(`created label: ${lbl.name}`);
              } else {
                core.info(`label exists: ${lbl.name}`);
              }
            }