name: CI (pnpm monorepo)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    concurrency:
      group: api-factory-ci-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

      - name: Load TRACK into environment
        if: always()
        run: |
          if [ -f TRACK ]; then
            echo "TRACK=$(cat TRACK)" >> $GITHUB_ENV
          fi

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies (pnpm)
        run: pnpm install --frozen-lockfile

      - name: Lint (workspace)
        run: pnpm -w -r --if-present lint

      - name: Typecheck (workspace)
        run: pnpm -w -r --if-present typecheck

      - name: Test (workspace)
        run: pnpm -w -r --if-present test

      - name: Build (workspace)
        run: pnpm -w -r --if-present build

      - name: Optional smoke tests
        if: ${{ secrets.SMOKE_TARGET != '' }}
        env:
          SMOKE_TARGET: '${{ secrets.SMOKE_TARGET }}'
          SMOKE_API_KEY: '${{ secrets.SMOKE_API_KEY }}'
        run: |
          chmod +x ./scripts/smoke-test.sh
          ./scripts/smoke-test.sh "$SMOKE_TARGET" "$SMOKE_API_KEY"
