name: CI — Debug runner

on:
  push:
    branches: [ main ]

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - name: Print hello
        run: |
          echo "hello from debug workflow"
          uname -a
          date
