name: Docker CI (matrix, cached)

name: Docker CI (matrix, cached)

on:
  pull_request:
    branches: [main, develop]
    paths: ["apps/**", "packages/**", "pnpm-lock.yaml", "package.json", ".github/**"]
  push:
    branches: [main]
    paths: ["apps/**", "packages/**", "pnpm-lock.yaml", "package.json", ".github/**"]

name: Docker CI (matrix, cached)

on:
  pull_request:
    branches: [main, develop]
    paths: ["apps/**", "packages/**", "pnpm-lock.yaml", "package.json", ".github/**"]
  push:
    branches: [main]
    paths: ["apps/**", "packages/**", "pnpm-lock.yaml", "package.json", ".github/**"]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [api-cli, admin-web, web]
    name: Build Docker image - ${{ matrix.service }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Enable corepack & prepare pnpm
        run: |
          corepack enable
          corepack prepare pnpm@9.9.0 --activate

      - name: Install deps & build artifacts
        run: |
          pnpm i --frozen-lockfile
          pnpm -w -r build

      - name: Setup buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and cache image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: apps/${{ matrix.service }}/Dockerfile
          push: false
          tags: ghcr.io/${{ toLower(github.repository_owner) }}/${{ matrix.service }}:pr-${{ github.sha }}
          cache-from: "type=gha,scope=${{ matrix.service }}-cache"
          cache-to: "type=gha,mode=max,scope=${{ matrix.service }}-cache"
