name: Docker CI (cached)
on:
  pull_request:
    branches: [main, develop]
    paths: ["apps/**","packages/**","pnpm-lock.yaml","package.json",".github/**"]
  push:
    branches: [main]
    paths: ["apps/**","packages/**","pnpm-lock.yaml","package.json",".github/**"]

permissions:
  contents: read
  packages: write

jobs:
  api-cli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435
      - uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83
        with:
          context: .
          file: apps/api-cli/Dockerfile
          push: false
          tags: ghcr.io/${{ toLower(github.repository_owner) }}/api-cli:pr-${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  admin-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435
      - uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83
        with:
          context: .
          file: apps/admin-web/Dockerfile
          push: false
          tags: ghcr.io/${{ toLower(github.repository_owner) }}/admin-web:pr-${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
