name: Gitleaks
on:
  pull_request:
  push:
    branches: [main]
permissions: { contents: read }
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        with:
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@dcedce43c6f43de0b836d1fe38946645c9c638dc
        env:
          GITLEAKS_LICENSE: ""
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
