name: Release Gate Unlock

on:
  push:
    tags:
      - 'v*'

jobs:
  unlock:
    name: Unlock next release after tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        with:
          persist-credentials: true

      - name: Show triggered tag
        run: |
          echo "Triggered for tag: ${{ github.ref_name }}"

      - name: Ensure unlock script is executable
        run: |
          chmod +x scripts/unlock_next_release.sh

      - name: Run unlock script
        run: |
          scripts/unlock_next_release.sh "${{ github.ref_name }}"

      - name: Commit RELEASES changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add RELEASES || true
          if git diff --staged --quiet; then
            echo "No RELEASES changes to commit"
            echo "noop" > /tmp/noop
          else
            git commit -m "chore(release): unlock next release after ${{ github.ref_name }}"
          fi

      - name: Create Pull Request for RELEASES changes
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore(release): unlock next release after ${{ github.ref_name }}"
          branch: "release-gate/after-${{ github.ref_name }}"
          title: "chore(release): unlock next release after ${{ github.ref_name }}"
          body: |
            Automated update to RELEASES after unlocking next release for ${{ github.ref_name }}.
          base: main
