name: Release: Build, Publish & Smoke Test

on:
  push:
    branches: [ main ]
    tags: ['v*', 'release-*']

permissions:
  contents: read
  packages: write

jobs:
  build-publish-smoke:
    name: Build, Publish & Smoke Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

      - name: Setup Node 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Enable corepack & pnpm
        run: |
          corepack enable
          corepack prepare pnpm@9.9.0 --activate

      - name: Install workspace deps
        run: pnpm -w i --frozen-lockfile

      - name: Build workspace
        run: pnpm -w build

      - name: Login to ghcr
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push API image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile.api
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/api-factory-api:${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/api-factory-api:latest

      - name: Build & push Web image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile.web
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/api-factory-web:${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/api-factory-web:latest

      - name: Pull published images
        run: |
          docker pull ghcr.io/${{ github.repository_owner }}/api-factory-api:latest
          docker pull ghcr.io/${{ github.repository_owner }}/api-factory-web:latest

      - name: Run smoke containers
        run: |
          docker run -d --name smoke-api -p 8787:8787 ghcr.io/${{ github.repository_owner }}/api-factory-api:latest || docker start smoke-api
          docker run -d --name smoke-web -p 3000:80 ghcr.io/${{ github.repository_owner }}/api-factory-web:latest || docker start smoke-web
          # wait for API to become healthy
          for i in {1..12}; do
            curl -fsS http://127.0.0.1:8787/_api/healthz && break || sleep 5
          done

      - name: Run smoke tests
        run: |
          curl -fsS http://127.0.0.1:8787/_api/healthz
          curl -fsS http://127.0.0.1:3000/

      - name: Cleanup
        if: always()
        run: |
          docker rm -f smoke-api smoke-web || true
          docker image rm ghcr.io/${{ github.repository_owner }}/api-factory-api:latest ghcr.io/${{ github.repository_owner }}/api-factory-web:latest || true
