name: Scheduled CI monitor

on:
  schedule:
    - cron: '*/15 * * * *' # every 15 minutes
  workflow_dispatch: {}

permissions:
  issues: write
  actions: read

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure jq is available
        run: sudo apt-get update && sudo apt-get install -y jq curl

      - name: Run scheduled CI monitor
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./.github/scripts/ci-monitor-action.sh
