name: us-compliance-predeploy

on:
  pull_request:
    branches: [ main ]

jobs:
  compliance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - name: Validate OpenAPI (skip if missing)
        run: |
          if [ -f openapi.yaml ]; then
            pipx install openapi-spec-validator && openapi-spec-validator openapi.yaml
          else
            echo "No openapi.yaml found — skipping OpenAPI validation for PRs";
          fi
      - name: Check consent & audit logging
        run: python scripts/check_consent_logging.py --spec openapi.yaml
      - name: Verify compliance tags
        run: python scripts/check_compliance_tags.py --spec openapi.yaml --required HIPAA FTC FERPA SEC CFTC FAA EPA FCRA TILA ECOA ADA COPPA FOIA "NIST AI RMF" || true
      - name: Block on high-risk missing
        run: python scripts/block_on_missing.py --laws HIPAA SEC CFPB "Colorado SB 205"
