stages:
  - build
  - test
  - release

jobs:
  build:
    stage: build
    script:
      - echo "Building the project..."
      - ./scripts/build.sh

  test:
    stage: test
    script:
      - echo "Running tests..."
      - ./scripts/test.sh

  release:
    stage: release
    script:
      - echo "Releasing the project..."
      - ./scripts/release.sh